### ISSUE TITLE
Add LICENSE or COPYING file

### ISSUE THREAD

**Issue by CorruptedArk** [sliusar/zero_brightness_fixer#2]
Hi, first off, I want to say I appreciate this little program you wrote. It's solved this niche little problem for me. However, I think it would be helpful if you added a license like GPL, MIT, BSD, etc. It would help end users know what they're allowed to do with the software. As it stands now, no one other than yourself has a legal right to fork or distribute the source code. If you'd like, I would gladly submit a pull request with a recommended license.

**Comment by sliusar** [comment]
Done, MIT license added.
